login
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #147
Opened 2021-06-18 19:17 UTC by Loic-Code

2021-06-18 19:50 UTC, Serdar45000 approved these changes

2021-06-19 21:09 UTC, Thuydieutran commented on src/Controller/SecurityController.php
> +        // if ($this->getUser()) {
il faut pas mettre le code dans le commentaire.

2021-06-19 21:29 UTC, Thuydieutran requested changes

2021-06-19 21:29 UTC, Thuydieutran commented on templates/security/login.html.twig
> +					{#
Puisque tu n'as pas fait la fonctionalité de connexion "remember-me", cette partie de commentaire est inutile. Il faut que tu supprimes tout également.

2021-06-19 21:34 UTC, Thuydieutran requested changes

2021-06-19 21:34 UTC, Thuydieutran commented on templates/security/login.html.twig
> +					Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
Puisque tu n'as pas fait la fonctionalité de connexion "remember-me", cette partie de commentaire est inutile. Il faut que tu supprimes tout également.

2021-06-19 22:34 UTC, Thuydieutran approved these changes

2021-06-20 07:40 UTC, sblondeau approved these changes

2021-06-20 07:40 UTC, merged