11- Mes informations (user)
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #164
Opened 2021-06-23 18:51 UTC by eguesbaya

avec le style

2021-06-23 19:19 UTC, Serdar45000 submitted a review, later dismissed

2021-06-23 21:18 UTC, Thuydieutran approved these changes

2021-06-24 06:23 UTC, sblondeau requested changes

2021-06-24 06:23 UTC, sblondeau commented on templates/profile_client/index.html.twig
> +            <h3>{{ user.lastname }}</h3>
tu peux plutot faire direct un app.user.lastname ici, sans avoir besoin de passer $this->getUser() de ton controlleur à ta vue

2021-06-24 07:33 UTC, Serdar45000 approved these changes

2021-06-24 07:33 UTC, Thuydieutran approved these changes

2021-06-24 07:34 UTC, khadimb approved these changes

2021-06-24 07:41 UTC, sblondeau approved these changes

2021-06-24 07:42 UTC, merged