deny access to profile/coach for users who arent admin
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #181
Opened 2021-07-01 13:46 UTC by eguesbaya

2021-07-01 13:51 UTC, Serdar45000 submitted a review, later dismissed

2021-07-01 14:35 UTC, Thuydieutran approved these changes

2021-07-01 14:58 UTC, sblondeau requested changes

2021-07-01 14:58 UTC, sblondeau commented on src/Controller/ProfileCoachController.php
> +        $this->denyAccessUnlessGranted('ROLE_ADMIN');
fait plutot un @isGranted(ROLE_ADMIN) en annotation

2021-07-02 09:18 UTC, Thuydieutran approved these changes

2021-07-02 09:49 UTC, khadimb approved these changes

2021-07-02 10:09 UTC, sblondeau commented
creer ROLE_CLIENT et ROLE_COACH

2021-07-05 09:03 UTC, eguesbaya commented
J'ai renommé la branche et créé une nouvelle pull request

2021-07-05 09:03 UTC, closed without merging