Ajout activité Super Admin
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #224
Opened 2021-07-07 19:57 UTC by Serdar45000

2021-07-07 20:36 UTC, Thuydieutran submitted a review, later dismissed

2021-07-08 07:13 UTC, khadimb submitted a review, later dismissed

2021-07-08 08:32 UTC, sblondeau requested changes
je pense qu'il manque les Assert dans l'entity Activity

2021-07-08 14:05 UTC, Thuydieutran approved these changes

2021-07-08 14:08 UTC, Loic-Code approved these changes

2021-07-08 14:29 UTC, sblondeau approved these changes

2021-07-08 14:29 UTC, merged