21 superadmin bookings status
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #266
Opened 2021-07-11 16:07 UTC by Thuydieutran

2021-07-11 16:40 UTC, khadimb submitted a review, later dismissed

2021-07-11 17:51 UTC, Serdar45000 approved these changes

2021-07-12 07:28 UTC, sblondeau requested changes

2021-07-12 07:28 UTC, sblondeau commented on src/Entity/BookingStatus.php
> +     * @ORM\Column(type="string", length=255)
vu que tu as fais un form à la main coté vu, tu dois refaire une validation supplémentaire ici
https://symfony.com/doc/current/reference/constraints/Choice.html#supplying-the-choices-with-a-callback-function
(quand tu utilises le component form, c'est fait en automatiqeu)

2021-07-12 08:08 UTC, eguesbaya approved these changes

2021-07-12 08:09 UTC, Loic-Code submitted a review, later dismissed

2021-07-12 08:09 UTC, Serdar45000 approved these changes

2021-07-12 08:56 UTC, Loic-Code approved these changes

2021-07-12 08:57 UTC, khadimb approved these changes

2021-07-12 09:07 UTC, sblondeau approved these changes

2021-07-12 09:07 UTC, merged