S1 us02 activités
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #27
Opened 2021-06-03 19:29 UTC by eguesbaya

J'ai créé un tableau d'activités dans HomeController, pour émuler la future dase de donnée. La variable devra être retirée quand la base de donnée sera créée et connectée au projet.
Fichier Twig fonctionne et affiche les cards activités de façon responsive.
Arborescence de Thuy intégrée.

Besoin de surcharger les titres bootstrap.

2021-06-03 21:16 UTC, khadimb submitted a review, later dismissed
ok

2021-06-03 21:59 UTC, Loic-Code approved these changes

2021-06-03 21:59 UTC, Serdar45000 submitted a review, later dismissed
Ok super !

2021-06-04 07:03 UTC, sblondeau requested changes

2021-06-04 07:03 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $activities = [
non, justement il faut que tu créé l'entité et du coup ce tableau il peut aller dans la partie fixtures (tu as créé le fichier de fixtures mais il est vide)

2021-06-04 07:03 UTC, sblondeau commented on templates/home/_activities.html.twig
> +        {% for activity in activities %}
et donc la activities provient direct de la bdd

2021-06-04 07:03 UTC, sblondeau commented on templates/home/_activities.html.twig
> +<!-- card
code commenté

2021-06-04 07:03 UTC, sblondeau commented on composer.json
> +        "doctrine/doctrine-fixtures-bundle": "^3.4",
cette modif (update) du composer.json est inutile, ne touchez pas au composer.json sauf install de librairies pour votre projet, là doctrine-fixtures y est déjà. 
Je ne veux ni ce fichier, ni le composer.lock dans la pr

2021-06-04 07:28 UTC, eguesbaya commented on templates/home/_activities.html.twig
> +<!-- card
fixed

2021-06-04 07:30 UTC, eguesbaya commented on composer.json
> +        "doctrine/doctrine-fixtures-bundle": "^3.4",
Ok, c'est fixé. Comment je fais pour les enlever de la PR?

2021-06-04 15:02 UTC, eguesbaya commented on src/Controller/HomeController.php
> +        $activities = [
fixtures créées et appelées

2021-06-04 15:02 UTC, eguesbaya commented on templates/home/_activities.html.twig
> +        {% for activity in activities %}
yes c'est fait

2021-06-06 20:40 UTC, Thuydieutran approved these changes

2021-06-07 07:53 UTC, khadimb requested changes
Des choses a modifier sur certains fichiers

2021-06-08 12:14 UTC, khadimb submitted a review, later dismissed

2021-06-08 12:14 UTC, Thuydieutran submitted a review, later dismissed

2021-06-09 07:29 UTC, sblondeau requested changes

2021-06-09 07:29 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $activities = $this->getDoctrine()
utilise plutot ActivityRepository via l'injection de dépendance (en param de ta méhode)

2021-06-09 07:29 UTC, sblondeau commented on src/Controller/HomeController.php
> +            ->findAll();
ta liste d'activités a t-elle besoin d'etre ordonée alphabétiquement?

2021-06-09 07:29 UTC, sblondeau commented on templates/home/_activities.html.twig
> +        <div class="col-12 col-md-6 col-lg-4 card-group">
indiquer col-12 n'est pas nécessaire (comportement par défaut)

2021-06-09 08:02 UTC, eguesbaya commented on src/Controller/HomeController.php
> +            ->findAll();
non pas nécessairement

2021-06-09 08:21 UTC, khadimb approved these changes

2021-06-09 08:56 UTC, Thuydieutran approved these changes

2021-06-09 08:56 UTC, Serdar45000 approved these changes
Ok super

2021-06-09 08:57 UTC, khadimb approved these changes

2021-06-09 09:47 UTC, sblondeau requested changes

2021-06-09 09:47 UTC, sblondeau commented on src/Controller/HomeController.php
> +            ->findBy(['isFeatured' => 'true'], ['name' => 'ASC'], 6);
fais un constante MAX_ACTIVITIES plutot qu'un 6 en dur

2021-06-09 10:04 UTC, Thuydieutran approved these changes

2021-06-09 10:04 UTC, Serdar45000 approved these changes
OK Super !

2021-06-09 10:05 UTC, khadimb approved these changes

2021-06-09 10:07 UTC, Loic-Code approved these changes

2021-06-09 10:31 UTC, sblondeau approved these changes

2021-06-09 10:32 UTC, merged