fix definition des photos
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #277
Opened 2021-07-12 20:19 UTC by khadimb

2021-07-12 20:26 UTC, Thuydieutran approved these changes

2021-07-12 21:23 UTC, eguesbaya approved these changes

2021-07-12 21:32 UTC, sblondeau requested changes

2021-07-12 21:32 UTC, sblondeau commented on templates/home/_coach.html.twig
> +            <img src="https://cdn.pixabay.com/photo/2018/01/01/01/57/woman-3053492_960_720.jpg" class="card-img-top" alt="coach">
non l'image doit etre en local, dans assets/images, renommée de manière intelligible et faire moins de 200ko

2021-07-12 21:32 UTC, sblondeau commented on templates/profile_coach/_photo.html.twig
> +          <img src="https://bit.ly/36tqcf6" class="img-fluid" alt="coach">
idem

2021-07-13 08:29 UTC, Thuydieutran approved these changes

2021-07-13 08:30 UTC, eguesbaya submitted a review, later dismissed

2021-07-13 08:41 UTC, sblondeau requested changes
il reste une image trop grosse (à retirer peut-etre ? )

2021-07-13 08:59 UTC, Serdar45000 approved these changes

2021-07-13 09:00 UTC, Loic-Code approved these changes

2021-07-13 09:09 UTC, sblondeau approved these changes

2021-07-13 09:09 UTC, merged