US01_A_navbar
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #28
Opened 2021-06-03 22:20 UTC by Loic-Code

2021-06-03 22:21 UTC, khadimb approved these changes

2021-06-03 22:22 UTC, Serdar45000 submitted a review, later dismissed
Ok super !

2021-06-04 07:08 UTC, sblondeau requested changes

2021-06-04 07:08 UTC, sblondeau commented on assets/styles/navbar.scss
> +    color: $light !important;
pas de !important, tu peux surcharger la navbar sans ça

2021-06-04 07:08 UTC, sblondeau commented on assets/styles/variables.scss
> +$primary: #6bd736;
c'est plus une question, mais pourqoui la couleur primaire change ? elle a été définie dans la PR d'initialisation normalement. Si tu la modifies, faut que ce soit ok avec tout le monde dans le groupe

2021-06-04 07:08 UTC, sblondeau commented on templates/includes/_navbar.html.twig
> +				<button type="button" class="btn btn-success mx-1 button-login">S'INSCRIRE</button>
ça sera des liens pas des bouton là non ? tu fais un lien avec une class btn si tu veux un "style" de  bouton

2021-06-04 07:10 UTC, Loic-Code commented on assets/styles/variables.scss
> +$primary: #6bd736;
Ok avec le groupe.

2021-06-04 08:49 UTC, khadimb approved these changes

2021-06-04 08:50 UTC, Thuydieutran approved these changes

2021-06-04 08:53 UTC, eguesbaya approved these changes

2021-06-04 09:17 UTC, sblondeau approved these changes

2021-06-04 09:17 UTC, merged