US01_B_banner
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #29
Opened 2021-06-03 22:21 UTC by Loic-Code

2021-06-03 22:22 UTC, khadimb approved these changes

2021-06-03 22:23 UTC, Serdar45000 submitted a review, later dismissed
Ok super

2021-06-04 07:12 UTC, sblondeau requested changes
image banner beaucoup trop grosse!!! faites attention à ça je l'ai déjà répéter 100 fois ;-) 
200ko max

2021-06-04 07:12 UTC, sblondeau commented on assets/styles/banner.scss
> +    background: #7f7f7f;
couleurs en variable (variables scss pour le coup)

2021-06-04 07:12 UTC, sblondeau commented on assets/styles/banner.scss
> +    background: rgba(black, 0.5);
idem

2021-06-04 07:12 UTC, sblondeau commented on templates/includes/_banner.html.twig
> +        <p class="text-light describe-banner fst-italic">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or
ne mettez pas du lorem, mais le texte "final" qu'il faut penser à demander au client. En attendant mets un texte bateau du genre "Plateforme de mise en relation pour les coachs sportifs" et vous demander sa phrase d'accroche au client à la prochaine réu. L'idée c'est d'éviter d'oublier un lorem quelque part

2021-06-04 08:24 UTC, khadimb submitted a review, later dismissed

2021-06-04 08:25 UTC, Serdar45000 approved these changes
Ok super !

2021-06-04 08:26 UTC, eguesbaya approved these changes

2021-06-04 09:19 UTC, sblondeau submitted a review, later dismissed

2021-06-04 09:21 UTC, khadimb approved these changes

2021-06-04 09:22 UTC, eguesbaya approved these changes

2021-06-04 11:40 UTC, merged