Fix modification date de naissance
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #396
Opened 2021-07-19 14:51 UTC by Serdar45000

2021-07-19 14:52 UTC, Thuydieutran submitted a review, later dismissed

2021-07-20 07:26 UTC, eguesbaya submitted a review, later dismissed

2021-07-20 07:40 UTC, sblondeau requested changes

2021-07-20 07:40 UTC, sblondeau commented on templates/profile_coach/_preferences.html.twig
> +                            {{ activity.name }} <br>
pas de br pour pour faire ce genre de mise en page, un ul/li bien stylisé plutot

2021-07-20 09:54 UTC, khadimb approved these changes

2021-07-20 09:56 UTC, Thuydieutran approved these changes

2021-07-20 10:29 UTC, sblondeau approved these changes

2021-07-20 10:29 UTC, merged