Fix style profile client
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #402
Opened 2021-07-20 14:20 UTC by Thuydieutran

2021-07-20 14:27 UTC, Serdar45000 approved these changes

2021-07-20 14:30 UTC, eguesbaya approved these changes

2021-07-20 21:38 UTC, sblondeau requested changes

2021-07-20 21:38 UTC, sblondeau commented on templates/profile_client/index.html.twig
> +            <a href="{{ path('client_edit') }}" class="btn btn-success m-2 text-white"><i class="bi bi-pencil-square text-success text-white"></i> &nbsp; Mettre à jour</a>
enlève moi ce &nbsp; et met un mr-2 sur ton icone si tu veux un espacement

2021-07-21 07:16 UTC, Serdar45000 approved these changes

2021-07-21 07:17 UTC, eguesbaya approved these changes

2021-07-21 07:31 UTC, sblondeau requested changes

2021-07-21 07:31 UTC, sblondeau commented on templates/profile_client/_information.html.twig
> +                <h5 class="text-start mx-5">{{ app.user.lastname }}</h5>
non h3 était bien, tu as un h2 avant, il faut respecter l'ordre des titres. Si le style ne te plait pas, fait du CSS

2021-07-24 21:45 UTC, closed without merging