changement des termes ok
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #455
Opened 2021-07-23 12:51 UTC by khadimb

2021-07-23 13:11 UTC, Serdar45000 submitted a review, later dismissed

2021-07-23 13:18 UTC, eguesbaya requested changes
Pour bien faire il faudrait harmoniser ça avec la navbar admin, je crois qu'il y atoujours écrit Gestion dedans

2021-07-26 06:57 UTC, Thuydieutran approved these changes

2021-07-26 07:17 UTC, Loic-Code approved these changes

2021-07-26 07:21 UTC, sblondeau approved these changes

2021-07-26 07:21 UTC, merged