affichage 4 card
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #49
Opened 2021-06-10 14:14 UTC by khadimb

2021-06-10 14:18 UTC, Thuydieutran approved these changes

2021-06-10 14:51 UTC, eguesbaya requested changes

2021-06-10 14:51 UTC, eguesbaya commented on src/Controller/HomeController.php
> +            ->findBy([], ['id' => 'ASC'], 4);
le 4 à remplacer par ta constante

2021-06-10 20:07 UTC, Thuydieutran approved these changes

2021-06-10 20:29 UTC, Serdar45000 approved these changes

2021-06-11 07:06 UTC, sblondeau approved these changes

2021-06-11 07:10 UTC, sblondeau approved these changes

2021-06-11 07:11 UTC, merged