Page contact & vérification données
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #50
Opened 2021-06-10 21:57 UTC by Serdar45000

2021-06-11 07:41 UTC, khadimb submitted a review, later dismissed

2021-06-11 07:44 UTC, Loic-Code approved these changes

2021-06-11 08:15 UTC, eguesbaya commented
Aucun lien dirigeant vers cette page dans notre site. A réfléchir

2021-06-11 08:19 UTC, eguesbaya approved these changes

2021-06-11 08:56 UTC, sblondeau requested changes

2021-06-11 08:56 UTC, sblondeau commented on src/Entity/Contact.php
> +     *      min = 3,
j'ai répété une dizaine de fois de ne pas mettre de taille min sur les champs s'il n'ya pas de nécessité
là les personnes avec un nom/prenom de 1 ou 2 lettres ne peuvent pas utiliser ton site ;-)

2021-06-11 08:56 UTC, sblondeau commented on src/Entity/Contact.php
> +     *      min = 8,
idem, tu peux avoir des num de tel courts, enlève le min

2021-06-11 09:03 UTC, Loic-Code approved these changes

2021-06-11 09:03 UTC, eguesbaya approved these changes

2021-06-13 21:53 UTC, sblondeau approved these changes

2021-06-13 21:53 UTC, merged