FIX: activités responsive
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #84
Opened 2021-06-16 10:10 UTC by eguesbaya

2021-06-16 10:15 UTC, khadimb submitted a review, later dismissed

2021-06-16 10:17 UTC, Thuydieutran submitted a review, later dismissed

2021-06-16 14:38 UTC, sblondeau requested changes

2021-06-16 14:38 UTC, sblondeau commented on src/DataFixtures/ActivityFixtures.php
> +            $activity->setPhoto('https: //bit.ly/3gwemH4');
un espace en trop dans ton url

2021-06-16 14:38 UTC, sblondeau commented on templates/home/_activities.html.twig
> +                        <img src="https://bit.ly/3gwemH4" class="card-img-top h-100" alt="{{ activity.name }}">
pas d'intéret de laisser l'image en dur si tu la mets dans les fixtures ;-) donc ça devrait etre {{ activity.photo }}

2021-06-16 15:01 UTC, eguesbaya commented on templates/home/_activities.html.twig
> +                        <img src="https://bit.ly/3gwemH4" class="card-img-top h-100" alt="{{ activity.name }}">
ok mais ça n'affiche rien quand je fais ça...

2021-06-16 21:24 UTC, Serdar45000 approved these changes

2021-06-17 08:12 UTC, khadimb approved these changes

2021-06-17 08:44 UTC, sblondeau approved these changes

2021-06-17 08:45 UTC, merged