fix bg et bg contact
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #87
Opened 2021-06-16 13:09 UTC by Loic-Code

2021-06-16 13:11 UTC, khadimb approved these changes

2021-06-16 13:19 UTC, eguesbaya submitted a review, later dismissed

2021-06-16 13:19 UTC, Thuydieutran approved these changes

2021-06-16 14:40 UTC, sblondeau requested changes

2021-06-16 14:40 UTC, sblondeau commented on assets/styles/app.scss
> +    background-color: #fffafa;
couleur CSS en variable

2021-06-16 14:40 UTC, sblondeau commented on assets/styles/app.scss
> +    background-image: url("https://transparenttextures.com/patterns/clean-gray-paper.png");
enregistre plutot l'image en local  dans assets/images

2021-06-16 14:41 UTC, sblondeau requested changes

2021-06-16 14:41 UTC, sblondeau commented on templates/contact/index.html.twig
>          <div class='row d-flex justify-content-center'>
il faut utiliser plutot des doubles quotes en HTML

2021-06-17 08:12 UTC, Serdar45000 approved these changes

2021-06-17 08:19 UTC, eguesbaya approved these changes

2021-06-17 08:40 UTC, sblondeau approved these changes

2021-06-17 08:40 UTC, merged