FIX: activity card img
WildCodeSchool/orleans-202103-php-project-coachmoi pull request #94
Opened 2021-06-18 08:40 UTC by eguesbaya

2021-06-18 08:43 UTC, Thuydieutran submitted a review, later dismissed

2021-06-18 08:45 UTC, Serdar45000 approved these changes

2021-06-18 08:55 UTC, sblondeau requested changes

2021-06-18 08:55 UTC, sblondeau commented on migrations/Version20210618080112.php
> +    public function up(Schema $schema): void
ta migration ne va pas, tu as des DROP dans le up... tu as fais un make:mig sans faire de d:m:m je pense ;-) 
à nettoyer, dans une migration, je ne veux que les SQL qui correspondent aux modif de BDD qui touche votre US

2021-06-21 14:39 UTC, Thuydieutran submitted a review, later dismissed

2021-06-21 14:40 UTC, Serdar45000 submitted a review, later dismissed

2021-06-22 06:52 UTC, sblondeau requested changes

2021-06-23 07:26 UTC, eguesbaya commented on migrations/Version20210621140624.php
>          // this up() migration is auto-generated, please modify it to your needs
c'est parce que tu m'as refusé ma PR à cause du fichier migration, donc j'ai remis le fichier migrations à jour

2021-06-23 08:28 UTC, khadimb submitted a review, later dismissed

2021-06-23 08:40 UTC, Thuydieutran approved these changes

2021-06-23 12:03 UTC, sblondeau requested changes
le code de ta PR ne modifie pas la base, je ne dois pas avoir de fichier de migration dedans. Retire le

2021-06-23 13:46 UTC, Serdar45000 submitted a review, later dismissed

2021-06-23 14:05 UTC, khadimb submitted a review, later dismissed

2021-06-23 14:25 UTC, sblondeau requested changes

2021-06-23 14:25 UTC, sblondeau commented on assets/styles/app.scss
> +/*.card-activity img {
pas de code commenté

2021-06-23 21:19 UTC, Thuydieutran approved these changes

2021-06-24 08:11 UTC, Serdar45000 approved these changes

2021-06-24 09:13 UTC, sblondeau approved these changes

2021-06-24 09:13 UTC, merged